export const vinyl = [
  {
    title: "Selling Dogma",
    artist: "The Clouds",
    price: 44.99,
    image: "vinyl1.png",
    year: 2003,
    genre: "rock",
    stock: 12,
  },
  {
    title: "Echoes in Transit",
    artist: "Silver Meadow",
    price: 38.59,
    image: "vinyl2.png",
    year: 2012,
    genre: "indie",
    stock: 12,
  },
  {
    title: "Midnight Parallels",
    artist: "Neon Grove",
    price: 40.99,
    image: "vinyl3.png",
    year: 2020,
    genre: "ambient",
    stock: 12,
  },
  {
    title: "Paper Skies",
    artist: "The Ivory Youth",
    price: 42.45,
    image: "vinyl4.png",
    year: 2010,
    genre: "rock",
    stock: 12,
  },
  {
    title: "Lost Cartography",
    artist: "Atlas Hills",
    price: 39.99,
    image: "vinyl5.png",
    year: 2007,
    genre: "folk",
    stock: 12,
  },
  {
    title: "Seaside Reflections",
    artist: "Drifted Pines",
    price: 41.59,
    image: "vinyl6.png",
    year: 2015,
    genre: "ambient",
    stock: 12,
  },
  {
    title: "Quiet Wars",
    artist: "Northern Glow",
    price: 37.66,
    image: "vinyl7.png",
    year: 2009,
    genre: "indie",
    stock: 12,
  },
  {
    title: "Blossom and Rust",
    artist: "Faded Echoes",
    price: 45.99,
    image: "vinyl8.png",
    year: 2017,
    genre: "indie",
    stock: 12,
  },
  {
    title: "Broken Glow",
    artist: "Static Empire",
    price: 43.99,
    image: "vinyl9.png",
    year: 2014,
    genre: "punk",
    stock: 12,
  },
  {
    title: "Dreams of Glass",
    artist: "Wild Lanterns",
    price: 46.69,
    image: "vinyl10.png",
    year: 2019,
    genre: "indie",
    stock: 12,
  },
];
